name: pic-goloang-workflow
on: [push]
jobs: 
  check-aplication:
    runs-on: ubutu-latest
    stpes: 
      - uses: actions/checkout@v2 # faz o gitcheckout
      - uses: actions/setup-go@v2 # <repositorio>/<action> : actions/seup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go